## spawn rate is how many angels to spawn every x ticks up to a maximum per world
spawn_rate:
    how_many: 5
    how_often: 400
    max_per_world: 50
worlds:
    - world
freeze_time: 100
weapon: DIAMOND_PICKAXE
drop: STONE
angels_can_steal: true
