## spawn rate is how many angels to spawn every x ticks up to a maximum per world
angels:
    spawn_rate:
        how_many: 5
        how_often: 400
        max_per_world: 50
    worlds:
        - world
    freeze_time: 100
    weapon: DIAMOND_PICKAXE
    drops:
        - COBBLESTONE
        - STONE
    angels_can_steal: true
ice_warriors:
    spawn_rate:
        how_many: 3
        how_often: 400
        max_per_world: 25
    worlds:
        - world
    drops:
        - ICE
        - PACKED_ICE
        - SNOW_BLOCK
cybermen:
    spawn_rate:
        how_many: 2
        how_often: 400
        max_per_world: 15
    worlds:
        - world
    drops:
        - REDSTONE
        - STONE_BUTTON
    can_upgrade: true
empty_child:
    spawn_rate:
        how_many: 2
        how_often: 400
        max_per_world: 15
    worlds:
        - world
    drops:
        - COOKED_BEEF
        - SUGAR
always_use_leather: false