## spawn rate is how many angels to spawn every x ticks up to a maximum per world
angels:
    spawn_rate:
        how_many: 2
        how_often: 400
        max_per_world: 20
    worlds:
        - world
    freeze_time: 100
    weapon: DIAMOND_PICKAXE
    drops:
        - COBBLESTONE
        - STONE
    angels_can_steal: true
cybermen:
    spawn_rate:
        how_many: 2
        how_often: 400
        max_per_world: 10
    worlds:
        - world
    drops:
        - REDSTONE
        - STONE_BUTTON
    can_upgrade: true
daleks:
    spawn_rate:
        how_many: 2
        how_often: 400
        max_per_world: 20
    worlds:
        - world
    drops:
        - SLIME_BALL
        - ROTTEN_FLESH
empty_child:
    spawn_rate:
        how_many: 2
        how_often: 400
        max_per_world: 10
    worlds:
        - world
    drops:
        - COOKED_BEEF
        - SUGAR
ice_warriors:
    spawn_rate:
        how_many: 2
        how_often: 400
        max_per_world: 20
    worlds:
        - world
    drops:
        - ICE
        - PACKED_ICE
        - SNOW_BLOCK
silurians:
    spawn_rate:
        how_many: 2
        how_often: 400
        max_per_world: 20
    worlds:
        - world
    drops:
        - GOLD_NUGGET
        - FEATHER
sontarans:
    spawn_rate:
        how_many: 2
        how_often: 400
        max_per_world: 20
    worlds:
        - world
    drops:
        - POTATO_ITEM
        - MILK_BUCKET
    can_tame: true
zygons:
    spawn_rate:
        how_many: 2
        how_often: 400
        max_per_world: 10
    worlds:
        - world
    drops:
        - PAINTING
        - SAND
