## spawn rate is how many angels to spawn every x ticks up to a maximum per world
config_version: 2.0
spawn_rate:
    how_many: 2
    how_often: 400
    default_max: 0
angels:
    worlds:
        world: 20
    freeze_time: 100
    weapon: DIAMOND_PICKAXE
    drops:
        - COBBLESTONE
        - STONE
    angels_can_steal: true
cybermen:
    worlds:
        world: 10
    drops:
        - REDSTONE
        - STONE_BUTTON
    can_upgrade: true
daleks:
    worlds:
        world: 20
    drops:
        - SLIME_BALL
        - ROTTEN_FLESH
empty_child:
    worlds:
        world: 10
    drops:
        - COOKED_BEEF
        - SUGAR
ice_warriors:
    worlds:
        world: 20
    drops:
        - ICE
        - PACKED_ICE
        - SNOW_BLOCK
silurians:
    worlds:
        world: 20
    drops:
        - GOLD_NUGGET
        - FEATHER
sontarans:
    worlds:
        world: 20
    drops:
        - POTATO_ITEM
        - MILK_BUCKET
    can_tame: true
vashta_nerada:
    worlds:
        world: 10
    drops:
        - BONE
        - LEATHER
zygons:
    worlds:
        world: 10
    drops:
        - PAINTING
        - SAND
