author: eccentric_nz
description: Weeping Angel add-on for the TARDIS plugin
main: me.eccentric_nz.tardisweepingangels.TARDISWeepingAngels
name: TARDISWeepingAngels
load: POSTWORLD
version: '1.2.2'
website: http://dev.bukkit.org/bukkit-plugins/tardisweepingangels
dev-url: http://dev.bukkit.org/bukkit-plugins/tardisweepingangels
url: http://dev.bukkit.org/bukkit-plugins/tardisweepingangels
softdepend: [TARDIS]
permissions:
    tardisweepingangels.spawn:
        description: Allow players to spawn Weeping Angels, Cybermen or Ice Warriors.
        default: op
    tardisweepingangels.disguise:
        description: Allow players to disguise themselves as Weeping Angels, Cybermen or Ice Warriors.
        default: op
    tardisweepingangels.count:
        description: Allow players to use the count command.
        default: op
    tardisweepingangels.admin:
        description: Allow players to alter plugin settings.
        default: op
commands:
    angel:
        aliases: [tangel,tardisangel]
        description: Spawns a Weeping Angel on the block you are targeting.
        usage: /<command>
        permission: tardisweepingangels.spawn
        permission-message: You don't have the permission <permission> to use this command
    warrior:
        aliases: [twarrior,tardiswarrior,ice]
        description: Spawns an Ice Warrior on the block you are targeting.
        usage: /<command>
        permission: tardisweepingangels.spawn
        permission-message: You don't have the permission <permission> to use this command
    cyberman:
        aliases: [tcyberman,tardiscyberman,cyber]
        description: Spawns an Ice Warrior on the block you are targeting.
        usage: /<command>
        permission: tardisweepingangels.spawn
        permission-message: You don't have the permission <permission> to use this command
    angeldisguise:
        aliases: [tardisangeldisguise,angeld]
        description: Sets a player's armour so that they are disguised as a Weeping Angel.
        usage: /<command> [on|off]
        permission: tardisweepingangels.disguise
        permission-message: You don't have the permission <permission> to use this command
    icedisguise:
        aliases: [warriordisguise,iced]
        description: Sets a player's armour so that they are disguised as an Ice Warrior.
        usage: /<command> [on|off]
        permission: tardisweepingangels.disguise
        permission-message: You don't have the permission <permission> to use this command
    cyberdisguise:
        aliases: [cyberd,cybermandisguise,cybermand]
        description: Sets a player's armour so that they are disguised as a Cyberman.
        usage: /<command> [on|off]
        permission: tardisweepingangels.disguise
        permission-message: You don't have the permission <permission> to use this command
    angelcount:
        aliases: [cybercount,icecount,acount,ccount,icount]
        description: Reports the current number of the specifed monster in the specified world.
        usage: /<command> [a|c|i] [world]
        permission: tardisweepingangels.count
        permission-message: You don't have the permission <permission> to use this command
    twa:
        aliases: [aadmin,angeladmin,tardisweepingangels]
        description: Add or remove worlds to the worlds list for the specified monster.
        usage: /<command> [a|c|i] [add|remove] [world]
        permission: tardisweepingangels.count
        permission-message: You don't have the permission <permission> to use this command
