authors: [eccentric_nz]
main: me.eccentric_nz.tardisweepingangels.TARDISWeepingAngelsPlugin
name: TARDISWeepingAngels
description: Weeping Angel add-on for the TARDIS plugin
version: ${project.version}
api-version: 1.17
load: POSTWORLD
softdepend: [TARDISChunkGenerator,WorldGuard]
website: http://tardisjenkins.duckdns.org:8080/job/TARDISWeepingAngels/
dev-url: https://github.com/eccentricdevotion/TARDISWeepingAngels/
url: http://eccentricdevotion.github.io/TARDIS/
permissions:
  tardisweepingangels.k9:
    description: Allows a player to have a K9 companion.
    default: op
  tardisweepingangels.spawn:
    description: Allows a player to spawn a monster.
    default: op
    children:
      tardisweepingangels.spawn.angel: true
      tardisweepingangels.spawn.cyberman: true
      tardisweepingangels.spawn.dalek: true
      tardisweepingangels.spawn.empty: true
      tardisweepingangels.spawn.ice: true
      tardisweepingangels.spawn.judoon: true
      tardisweepingangels.spawn.k9: true
      tardisweepingangels.spawn.ood: true
      tardisweepingangels.spawn.silent: true
      tardisweepingangels.spawn.silurian: true
      tardisweepingangels.spawn.sontaran: true
      tardisweepingangels.spawn.strax: true
      tardisweepingangels.spawn.toclafane: true
      tardisweepingangels.spawn.vashta: true
      tardisweepingangels.spawn.zygon: true
  tardisweepingangels.follow:
    description: Allows a player to make an Ood, Judoon, or K9 follow them.
    default: op
    children:
      tardisweepingangels.follow.judoon: true
      tardisweepingangels.follow.k9: true
      tardisweepingangels.follow.ood: true
  tardisweepingangels.remove:
    description: Allows a player to remove an Ood, Judoon, or K9.
    default: op
    children:
      tardisweepingangels.remove.judoon: true
      tardisweepingangels.remove.k9: true
      tardisweepingangels.remove.ood: true
  tardisweepingangels.build:
    description: Allows a player to build a monster (Weeping Angel, Ood, Judoon, K9).
    default: op
    children:
      tardisweepingangels.build.angel: true
      tardisweepingangels.build.judoon: true
      tardisweepingangels.build.k9: true
      tardisweepingangels.build.ood: true
  tardisweepingangels.disguise:
    description: Allows a player to disguise themselves as a monster.
    default: op
  tardisweepingangels.count:
    description: Allows a player to use the count command.
    default: op
  tardisweepingangels.kill:
    description: Allows a player to use the kill command.
    default: op
  tardisweepingangels.admin:
    description: Allows a player to alter plugin settings.
    default: op
commands:
  tardisweepingangels:
    aliases: [twa]
    description: Manipulates TARDISWeepingAngels monsters with various arguments (spawn, kill, remove, count, disguise, equip, etc.).
    usage: "Usage: /<command> <subcommand> <monster> <world> <max>"
